apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talkflow-ingress
spec:
  rules:
    - host: e523be3986f1.ngrok-free.app  #change it with your url to host on, it can be localhost
      http:
        paths:
          # Backend API (must be FIRST so it has precedence)
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: backend
                port:
                  number: 8000
          # Everything else → frontend
          - pathType: Prefix
            path: /
            backend:
              service:
                name: frontend
                port:
                  number: 80