# ###### Not using it as we are using storage-pv-pvc.yaml now ##########


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ollama-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:   # Minikube will use hostPath for local storage
#     path: /data/ollama
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
